In [1]:
import pandas as pd
import numpy as np
import json
import warnings
warnings.filterwarnings("ignore")

In [2]:

with open('dry.json', 'r') as f:
    data= f.read()
with open('oil.json', 'r') as f:
    oil= f.read()
with open('acne.json', 'r') as f:
    acne= f.read()
with open('age.json', 'r') as f:
    age= f.read()
with open('bright.json', 'r') as f:
    bright= f.read()
with open('pores.json', 'r') as f:
    pores= f.read()
with open('scar.json', 'r') as f:
    scar= f.read()
with open('sens.json', 'r') as f:
    sens= f.read()
with open('spots.json', 'r') as f:
    spots= f.read()
with open('text.json', 'r') as f:
    text= f.read()

In [3]:
dry = json.loads(data)
oil = json.loads(oil)
acne = json.loads(acne)
age = json.loads(age)
bright = json.loads(bright)
pores = json.loads(pores)
scar = json.loads(scar)
sens = json.loads(sens)
spots = json.loads(spots)
text = json.loads(text)

In [4]:

oil_keys = oil.keys()
lista_1 = []
lista_2 = []
lista_3 = []

for key in oil_keys:
    if len(oil[key]) > 0:
        lista_1.append(oil[key][0][0][0])
    if len(oil[key]) > 1:
        lista_2.append(oil[key][1][0][0])
    if len(oil[key]) > 2:
        lista_3.append(oil[key][2][0][0])


len(lista_1)

156

In [5]:
data = {'lista_1': lista_1, 'lista_2': lista_2, 'lista_3': lista_3}

In [6]:
df = pd.DataFrame(data)

In [7]:
df['skin'] = ['oil'] * len(df.index)

In [8]:
df.head()

,lista_1,lista_2,lista_3,skin
0,Face Cleanser,CeraVe,Renewing SA Cleanser,oil
1,Day Moisturizer,CeraVe,Facial Moisturizing Lotion AM with Sunscreen B...,oil
2,Serum,Glow Recipe,Watermelon Glow Niacinamide Dew Drops,oil
3,Serum,Good (Skin) Days,C’s The Day Serum,oil
4,Toner,COSRX,Galactomyces 95 Tone Balancing Essence,oil

In [10]:

dry_keys = dry.keys()
lista_d1 = []
lista_d2 = []
lista_d3 = []

for key in dry_keys:
    if len(dry[key]) > 0:
        lista_d1.append(dry[key][0][0][0])
    if len(dry[key]) > 1:
        lista_d2.append(dry[key][1][0][0])
    if len(dry[key]) > 2:
        lista_d3.append(dry[key][2][0][0])

In [16]:
data2 = {'lista_1': lista_d1, 'lista_2': lista_d2, 'lista_3': lista_d3}
df2 = pd.DataFrame(data2)
df2['skin'] = ['dry'] * len(df2.index)

In [17]:
df2

,lista_1,lista_2,lista_3,skin
0,Face Cleanser,CeraVe,Renewing SA Cleanser,dry
1,Day Moisturizer,CeraVe,Facial Moisturizing Lotion AM with Sunscreen B...,dry
2,Serum,Glow Recipe,Watermelon Glow Niacinamide Dew Drops,dry
3,Eye Moisturizer,Beauty of Joseon,Revive Eye Serum : Ginseng + Retinal,dry
4,Eye Mask,Winky Lux,Wakey Wakey Hydrogel Under Eye Patches,dry
...,...,...,...,...
206,General Moisturizer,Benefit Cosmetics,Total Moisture Facial Cream,dry
207,Face Cleanser,Coxir,Ceramide Micro Derma Cleanser,dry
208,Sunscreen,Differin,Oil Absorbing Moisturizer with Sunscreen SPF 30,dry
209,Other Haircare,Bumble and bumble.,Curl Butter Masque,dry
210,Bath & Body,Gehwol,Fusskraft Soft Feet Cream,dry

In [23]:

acne_keys = acne.keys()
lista_a1 = []
lista_a2 = []
lista_a3 = []

for key in acne_keys:
        if len(acne[key]) > 0:
            if len(acne[key][0]) > 0:
                if len(acne[key][0][0]) > 0:
                    lista_a1.append(acne[key][0][0][0])

        if len(acne[key]) > 1:
            if len(acne[key][1]) > 0:
                if len(acne[key][1][0]) > 0:
                    lista_a2.append(acne[key][1][0][0])

        if len(acne[key]) > 2:
            if len(acne[key][2]) > 0:
                if len(acne[key][2][0]) > 0:
                    lista_a3.append(acne[key][2][0][0])

In [28]:
data3 = {'lista_1': lista_a1, 'lista_2': lista_a2, 'lista_3': lista_a3}
df3 = pd.DataFrame(data3)
df3['skin'] = ['acne'] * len(df3.index)

In [30]:
df3.head()

         lista_1            lista_2                              lista_3  skin
0  Face Cleanser             CeraVe                 Renewing SA Cleanser  acne
1          Toner           I'm From                           Rice Toner  acne
2          Serum  Naturium Skincare               Alpha Arbutin Serum 2%  acne
3          Serum              Azure  Hyaluronic and Retinol Facial Serum  acne
4          Serum             Kracie              Antioxidant Boost Serum  acne

In [31]:

age_keys = age.keys()
lista_g1 = []
lista_g2 = []
lista_g3 = []

for key in age_keys:
    if len(age[key]) > 0:
        lista_g1.append(age[key][0][0][0])
    if len(age[key]) > 1:
        lista_g2.append(age[key][1][0][0])
    if len(age[key]) > 2:
        lista_g3.append(age[key][2][0][0])

In [33]:
data4 = {'lista_1': lista_g1, 'lista_2': lista_g2, 'lista_3': lista_g3}
df4 = pd.DataFrame(data4)
df4['skin'] = ['age'] * len(df4.index)

In [47]:
bright_keys = bright.keys()
lista_b1 = []
lista_b2 = []
lista_b3 = []

for key in bright_keys:
    if len(bright[key]) > 0:
        lista_b1.append(bright[key][0][0][0])
    if len(bright[key]) > 1:
        lista_b2.append(bright[key][1][0][0])
    if len(bright[key]) > 2:
        lista_b3.append(bright[key][2][0][0])

In [48]:
data5 = {'lista_1': lista_b1, 'lista_2': lista_b2, 'lista_3': lista_b3}
df5 = pd.DataFrame(data5)
df5['skin'] = ['bright'] * len(df5.index)

In [50]:
df5.tail()

,lista_1,lista_2,lista_3,skin
301,Lip Makeup,Yves Saint Laurent,The Slim Velvet Radical Matte Lipstick,bright
302,Face Cleanser,AMOREPACIFIC,Treatment Enzyme Cleansing Foam,bright
303,Lip Makeup,skinChemists,Rose Quartz Lip Plump,bright
304,Sunscreen,Elizabeth Arden,Eight Hour® Cream Sun Defense for Face SPF 50 ...,bright
305,Bath & Body,Neutrogena,Cica-Balm Intense Repair,bright

In [51]:
pores_keys = pores.keys()
lista_p1 = []
lista_p2 = []
lista_p3 = []

for key in pores_keys:
    if len(pores[key]) > 0:
        lista_p1.append(pores[key][0][0][0])
    if len(pores[key]) > 1:
        lista_p2.append(pores[key][1][0][0])
    if len(pores[key]) > 2:
        lista_p3.append(pores[key][2][0][0])

In [52]:
data6 = {'lista_1': lista_p1, 'lista_2': lista_p2, 'lista_3': lista_p3}
df6 = pd.DataFrame(data6)
df6['skin'] = ['pores'] * len(df6.index)

In [56]:
df6[df6['lista_2']== "Paula's Choice"]

,lista_1,lista_2,lista_3,skin
61,Facial Treatment,Paula's Choice,RESIST Advanced Smoothing Treatment 10% AHA,pores
101,Exfoliator,Paula's Choice,CALM 1% BHA Sensitive Skin Exfoliant,pores

In [ ]:
scar_keys = scar.keys()
lista_s1 = []
lista_s2 = []
lista_s3 = []

for key in scar_keys:
    if len(scar[key]) > 0:
        lista_s1.append(scar[key][0][0][0])
    if len(pores[key]) > 1:
        lista_s2.append(scar[key][1][0][0])
    if len(pores[key]) > 2:
        lista_s3.append(scar[key][2][0][0])